name: Generate Snake

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Generate snake
        uses: Platane/snk@v3
        with:
          github_user_name: Y1ki
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: output
